logging:
  config: classpath:log4j2.xml

spring:
  datasource:
    url: jdbc:mysql://mysql-rds.cuwguiwtvuh1.ap-northeast-2.rds.amazonaws.com:3306/app_message
    username: ufms2021
    password: ufms2021
    driver-class-name: com.mysql.cj.jdbc.Driver